In [1]:
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../00_data/14_output/FsAMIs_0903_pop_ko.csv')
df.loc[df['factor'] == 'gdp', 'factor'] = 'GDP'
df.loc[df['factor'] == 'mental_health_providers', 'factor'] = 'MHP'
df.loc[df['factor'] == 'DEPRESSION', 'factor'] = 'DEP'
df.loc[df['factor'] == 'noise50n', 'factor'] = 'NOI'
df.loc[df['factor'] == 'BINGE', 'factor'] = 'ED'
df.loc[df['factor'] == 'FFR20', 'factor'] = 'FFR'
df.loc[df['factor'] == 'LPA', 'factor'] = 'PI'

In [3]:
my_factors = ["DEP", "ED", "PI", "MHP", "GDP", "NOI"]

In [12]:
df_raw = pd.read_csv("../00_data/13_final/cbsa_level.csv")

data = df.merge(df_raw[['cbsacode','TotalPopulation']])[['cbsacode','factor','TotalPopulation','FsAMI']].copy()

In [16]:
from scipy.stats import spearmanr

results = []
for fac in my_factors:
    sub = data[data["factor"] == fac]
    if len(sub) > 1:  # need at least 2 rows
        rho, pval = spearmanr(sub["TotalPopulation"], sub["FsAMI"])
        results.append({"factor": fac, "rho": rho, "pval": pval})

results_df = pd.DataFrame(results)
print(results_df)

results_df.to_csv('../00_data/14_output/population_rank.csv',index=False)

  factor       rho      pval
0    DEP  0.084559  0.012343
1     ED  0.021939  0.516912
2     PI -0.036146  0.285509
3    MHP  0.024484  0.469746
4    GDP -0.003248  0.923561
5    NOI  0.043754  0.196004

In [6]:
data

,DEP,ED,PI,MHP,GDP,NOI,cbsacode,TotalPopulation
0,7630.409,8802.089,9800.073,154.0,3439940.0,3717.083034,10100.0,42037
1,20954.336,12865.346,19105.424,288.0,3442875.0,3744.330966,10140.0,77038
2,43682.746,33724.319,49045.578,264.0,9606966.0,19453.578040,10180.0,179308
3,11327.877,5263.458,12433.966,225.0,2564945.0,2481.170945,10220.0,38141
4,23754.647,16559.256,26021.688,250.0,3938601.0,5334.595050,10300.0,98567
...,...,...,...,...,...,...,...,...
870,107573.664,70236.063,128537.013,1306.0,19770709.0,35991.149063,49660.0,426279
871,41820.750,33171.767,48250.135,551.0,8743275.0,24140.378031,49700.0,182813
872,40529.190,35748.824,65054.546,133.0,9907647.0,42701.812167,49740.0,207842
873,22217.154,15328.114,24628.318,160.0,4880613.0,5791.755148,49780.0,86113
874,3171.421,2021.954,6467.483,0.0,834289.0,349.529361,49820.0,13849