In [36]:
import pandas as pd

In [37]:
chr = pd.read_csv('../00_data/12_intermediate/chr.csv')
gdp = pd.read_csv('../00_data/12_intermediate/gdp.csv')
noise = pd.read_csv('../00_data/12_intermediate/noise.csv')
place = pd.read_csv('../00_data/12_intermediate/place.csv')

res = pd.read_excel('../00_data/11_raw/2025-food-environment-atlas-data.xlsx', sheet_name="RESTAURANTS",skiprows=1)

In [38]:
chr2022 = chr.loc[chr['year']==2022]
chr_renamed = chr2022[['fipscode',
       'adult_smoking', 'adult_obesity', 'excessive_drinking',
       'diabetes_prevalence', 'some_college',
       'unemployment', 'children_single_parent', 'mental_health_providers',
       'median_household_income', 'driving_alone_to_work', 'sti']].rename(columns={'fipscode': 'FIPS'})

place_renamed = place.rename(columns={'LocationID': 'FIPS'})

gdp2022 = gdp.loc[gdp['year']==2022]
gdp_renamed = gdp2022.rename(columns={'GeoFIPS': 'FIPS'})


noise['geoid_short'] = noise['geoid_short'].astype(str)

def strip_zeros(x):
    return x.lstrip("0").rstrip("0")

noise['FIPS'] = noise['geoid_short'].apply(strip_zeros)

noise_select = noise[['coverage_50','coverage_60', 'coverage_70', 'coverage_80', 'coverage_90', 
       'noise50n', 'noise60n','noise70n', 'noise80n', 'noise90n', 'FIPS']]

In [39]:
df1 = pd.merge(place_renamed,chr_renamed, on='FIPS', how='left')
df2 = pd.merge(df1, res[['FIPS','FFR20']], on='FIPS', how='left')
df3 = pd.merge(df2, gdp_renamed[['FIPS','gdp']], on='FIPS', how='left')
df3['FIPS'] = df3['FIPS'].astype(str)
final = pd.merge(df3, noise_select, on='FIPS', how='left')

In [40]:
final

,StateAbbr,LocationName,FIPS,TotalPopulation,BINGE,CSMOKING,DEPRESSION,DIABETES,LPA,OBESITY,...,coverage_50,coverage_60,coverage_70,coverage_80,coverage_90,noise50n,noise60n,noise70n,noise80n,noise90n
0,AK,Aleutians East,2013,3398,560.670,618.436,421.352,434.944,1032.992,1077.166,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AK,Aleutians West,2016,5122,1044.888,896.350,691.470,548.054,1367.574,1541.722,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AK,Anchorage,2020,287145,55993.275,38477.430,60874.740,22971.600,56567.565,84994.920,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AK,Bethel,2050,18257,3468.830,6079.581,4107.825,2428.181,6207.380,7503.627,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AK,Bristol Bay,2060,865,176.460,150.510,173.000,94.285,186.840,277.665,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3139,WY,Sweetwater,56037,41345,7938.240,7318.065,9013.210,4217.190,9261.280,15090.925,...,166680.258452,49899.968826,15487.437393,1218.442079,140.0,5383.728053,1116.699341,328.074876,40.555948,4.603305
3140,WY,Teton,56039,23287,4820.409,2654.718,4447.817,1839.673,3702.633,5262.862,...,31196.540103,6304.316617,369.000000,18.000000,0.0,804.428939,141.155460,10.876001,0.323381,0.000000
3141,WY,Uinta,56041,20712,3914.568,3686.736,4846.608,2154.048,5385.120,7373.472,...,61544.797830,16958.235114,5934.810009,387.960956,58.0,1531.873214,385.804989,123.159489,5.249862,0.410199
3142,WY,Washakie,56043,7719,1211.883,1335.387,1590.114,949.437,2022.378,2994.972,...,11212.993376,2599.774364,132.000000,33.000000,7.0,349.434177,54.242065,5.574692,1.160815,0.873946
3143,WY,Weston,56045,6860,1138.760,1207.360,1420.020,850.640,1728.720,2414.720,...,42641.212945,7620.502581,1182.053831,262.961039,57.0,248.394668,68.914164,5.872304,0.879569,0.150266

In [41]:
final.to_csv('../00_data/13_final/county_level.csv',index=False)

---

In [42]:
df = pd.read_csv('https://data.nber.org/cbsa-csa-fips-county-crosswalk/cbsa2fipsxw.csv')
park = pd.read_csv('../00_data/02_intermediate/cbsa_park.csv')

In [43]:
park

,CBSA Code,Num_Parks,Park_Area_Acres,Num_County,Num_Urban_Area,County_FIPS,Weighted_RESP,Weighted_UHI
0,10100,20,550.773301,1,1,46013,0.169974,-0.457756
1,10140,105,104080.141400,1,5,53027,0.308462,1.027633
2,10180,40,3252.752494,3,3,"48441, 48253, 48059",0.201492,1.137627
3,10220,3,87.794807,1,1,40123,0.297794,0.248900
4,10300,28,741.377599,1,2,26091,0.200000,0.060842
...,...,...,...,...,...,...,...,...
923,49660,93,5621.076757,2,2,"39099, 39155",0.203079,0.065809
924,49700,61,888.207710,2,4,"06115, 06101",0.390777,-2.361279
925,49740,57,434.539877,1,3,4027,0.286834,-0.973195
926,49780,20,15833.810080,1,2,39119,0.249417,-0.201614
927,49820,11,217.147500,1,1,48505,0.200000,0.613605

In [44]:
df["fipsstatecode"] = df["fipsstatecode"].astype(str)
df["fipscountycode"] = df["fipscountycode"].astype(str)

df["fipsstatecode"] = df["fipsstatecode"].str.zfill(2) 
df["fipscountycode"] = df["fipscountycode"].str.zfill(3)

df["countyfips"] = df["fipsstatecode"] + df["fipscountycode"]
df["FIPS"] = df["countyfips"].apply(strip_zeros)

park["cbsacode"] = park["CBSA Code"]

In [45]:
df4 = pd.merge(final,df[["FIPS", "cbsacode"]], on='FIPS', how='left')

In [46]:
cols = ['TotalPopulation','BINGE','CSMOKING','DEPRESSION','DIABETES','LPA','OBESITY',
        'adult_smoking','adult_obesity','excessive_drinking','diabetes_prevalence',
        'some_college','unemployment','children_single_parent','mental_health_providers',
        'median_household_income','driving_alone_to_work','sti','FFR20','gdp',
        'coverage_50','coverage_60','coverage_70','coverage_80','coverage_90',
        'noise50n','noise60n','noise70n','noise80n','noise90n']

tmp = df4.dropna(subset=['cbsacode']).copy()

# ensure numeric (non-numeric → NaN)
tmp[cols] = tmp[cols].apply(pd.to_numeric, errors='coerce')

# sum within CBSA (min_count=1 avoids all-NaN → 0)
clean = (tmp
         .groupby('cbsacode')[cols]
         .sum(min_count=1)
         .reset_index()).dropna()

df5 = pd.merge(clean,park[["cbsacode", "Park_Area_Acres"]], on='cbsacode', how='left')

In [47]:
df5.to_csv('../00_data/13_final/cbsa_level.csv',index=False)