# Merge again!

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
smart_path = '/Users/edison/Desktop/park/agg_smart_chr_new1.csv'
t19_path = '/Users/edison/Desktop/dp/twitter19_cbsa_depression_rates.csv'
t10_path = '/Users/edison/Desktop/dp/tweet2020_analysis.csv'

In [3]:
smart_df = pd.read_csv(smart_path)
t19_df = pd.read_csv(t19_path)
t10_df = pd.read_csv(t10_path)

In [4]:
smart_df['Data_value'] = smart_df['Data_value'].astype(float) / 100
smart_df = smart_df.drop(columns=['Data_value_unit'])

In [5]:
smart_df['year'] = smart_df['year'].astype(int).astype(str)
print(smart_df['year'].unique())

['2011' '2014' '2015' '2017' '2018' '2019' '2020' '2021' '2022' '2012'
 '2013' '2016']

In [6]:
t10_df = t10_df.drop(columns=['cbsatitle'])
t10_df = t10_df.drop(columns=['metropolitanmicropolitanstatis'])
t10_df

,cbsacode,depression,user_id,depression_rate,v002_rawvalue,v037_rawvalue,v009_rawvalue,v011_rawvalue,v012_rawvalue,v045_rawvalue,v004_rawvalue,v007_rawvalue,v021_rawvalue,v022_rawvalue,v023_rawvalue,v028_rawvalue,v043_rawvalue,v041_rawvalue,v003_rawvalue,CENSUS2010POP
0,10420.0,8,39,0.205128,87268.059400,58240.750100,173013.555500,195858.809,111324.954700,1957.518676,0.006515,5.745305e+05,5.758922e+05,1.945894e+05,43218.038,64030.281546,0.000000e+00,5.712920e+05,81398.628,703200
1,10500.0,4,15,0.266667,33627.313216,18073.870500,32678.588027,47206.727,17689.738858,1389.102350,0.001315,1.185530e+05,7.952461e+04,2.837964e+04,9865.678,22477.160398,0.000000e+00,1.857848e+05,21170.163,153857
2,10580.0,1,24,0.041667,110917.126900,64003.439900,189072.538638,222424.488,158365.739400,2233.395257,0.008414,7.340228e+05,6.528319e+05,2.751846e+05,43763.140,80305.574168,3.218712e+08,1.287547e+06,116186.034,870716
3,12060.0,48,486,0.098765,704567.332121,455224.078200,963351.570397,1392675.744,740003.530616,21640.878648,0.042887,4.294637e+06,3.473309e+06,1.745989e+06,326286.528,554777.011146,0.000000e+00,3.970489e+06,1000722.133,5298377
4,12100.0,1,10,0.100000,65413.527600,29781.885300,85816.600800,97169.000,60918.582200,1103.373359,0.002351,2.684954e+05,3.302661e+05,8.879119e+04,26999.630,41375.569391,1.831413e+08,8.184970e+05,57905.719,371814
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,46660.0,4,13,0.307692,26044.599392,14265.858176,34463.764464,41299.180,16477.232106,990.867864,0.000868,1.160292e+05,8.374227e+04,2.932177e+04,7558.108,16956.467756,0.000000e+00,1.523716e+05,26638.753,139588
87,46700.0,2,17,0.117647,59769.542400,28851.411200,66631.052800,103749.344,71963.190400,1908.822592,0.003456,2.904568e+05,3.150866e+05,9.219041e+04,28520.736,50745.085186,0.000000e+00,2.530742e+05,64895.008,413344
88,47260.0,27,170,0.158824,211511.480972,151082.675700,342753.535234,475181.105,265663.166097,9552.280605,0.015795,1.335754e+06,1.174754e+06,4.488527e+05,72779.011,193701.837471,7.826777e+08,8.597429e+05,230327.504,1693860
89,47900.0,45,401,0.112219,573286.485255,448931.822200,863743.921558,1350874.884,785722.012883,18777.039474,0.067928,4.408070e+06,4.500227e+06,2.542420e+06,209600.949,487666.391782,2.569000e+09,6.718948e+06,878906.936,5547495
90,49180.0,3,26,0.115385,108335.578400,60940.302000,157288.753300,172607.848,64041.045400,2812.914974,0.006369,5.375875e+05,4.790592e+05,1.475132e+05,39898.682,62936.938166,0.000000e+00,2.108734e+05,109573.770,640595

In [7]:
t10_df['cbsacode'] = t10_df['cbsacode'].astype(int)
print(t10_df['cbsacode'].unique())

[10420 10500 10580 12060 12100 12260 12420 12580 12940 13140 13780 13820
 14460 15380 16580 16700 16740 16980 17140 17410 17900 18140 19100 19430
 19740 19820 20100 20500 22180 22420 23060 23180 23540 24340 24660 24780
 24860 25620 26420 26620 26900 27140 27260 28140 28880 28940 29620 29820
 30780 31080 31140 32820 33100 33340 33460 33860 34980 35380 35620 36420
 36740 37980 38060 38300 38900 39300 39580 40060 40140 40900 41540 41700
 41740 41860 41940 42340 42660 41180 44340 44700 45060 45220 45300 45780
 46060 46220 46660 46700 47260 47900 49180]

In [8]:
t19_df['cbsa'] = t19_df['cbsa'].astype(int)
print(t19_df['cbsa'].unique())

[11460 16980 17140 17460 19100 19820 23420 25060 26380 26420 28140 29180
 29820 30820 31080 31420 33100 33460 35380 35620 36660 37980 38060 38900
 40060 40140 41180 41620 41740 41860 41940 42660 45940 46140 47260 47580]

In [9]:
t10_df['year'] = '2010'

In [10]:
t10_df.rename(columns={'depression_rate': 'Data_value'}, inplace=True)
t19_df.rename(columns={'depression rate': 'Data_value'}, inplace=True)
t10_df.rename(columns={'cbsacode': 'cbsacode'}, inplace=True)
t19_df.rename(columns={'cbsa': 'cbsacode'}, inplace=True)

In [11]:
smart_2011 = smart_df[smart_df['year'] == '2011'].copy()
smart_2011

,year,Locationdesc,Sample_Size,Data_value,Data_value_type,cbsacode,adult_population,adult_population18_65,population,total_65_and_older,...,total_physical_inactivity,total_poor_mental_health_days,total_poor_or_fair_health,total_poor_physical_health_days,total_premature_death,total_primary_care_physicians,total_rural,total_sexually_transmitted_infections,total_uninsured_adults,total_violent_crime
0,2011,"Aberdeen, SD Micropolitan Statistical Area",88,0.1675,Crude Prevalence,10100,30312.839,23626.885,39139.0,6685.954,...,8.501833e+03,3026.186667,3780.488759,3887.666667,2055.415364,529.733192,14460.996,79.103388,3323.081065,0.000000
9,2011,"Akron, OH Metropolitan Statistical Area",129,0.1618,Crude Prevalence,10420,543027.830,445615.135,699935.0,97412.695,...,1.367380e+05,82124.516670,69272.278180,74659.733330,49313.040360,8379.799700,88225.775,2233.122290,62880.485280,0.000000
26,2011,"Albuquerque, NM Metropolitan Statistical Area",720,0.2178,Crude Prevalence,10740,646133.629,542581.019,857903.0,103552.610,...,1.143223e+05,100593.186663,97397.000810,107603.960004,67685.000006,12356.913867,87515.802,3814.313737,146799.069605,0.000000
38,2011,"Allentown-Bethlehem-Easton, PA-NJ Metropolitan...",190,0.2059,Crude Prevalence,10900,631146.667,507590.995,816012.0,123555.672,...,1.586199e+05,97921.016673,87644.863465,101219.823327,52149.148954,9749.536861,157443.539,2027.464992,65794.536880,2208.332807
45,2011,"Anchorage, AK Metropolitan Statistical Area",241,0.1754,Crude Prevalence,11260,276129.709,248719.998,374553.0,27409.711,...,6.096059e+04,38633.686670,36882.397350,43922.323330,27108.017444,4395.286509,68165.241,2549.323455,54654.508780,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1546,2011,"Watertown, SD Micropolitan Statistical Area",72,0.1001,Crude Prevalence,47980,19678.336,15805.472,26168.0,3872.864,...,5.195081e+03,2093.440000,2105.581952,2355.120000,1665.017504,236.621884,6542.000,82.533872,2323.404384,0.000000
1558,2011,"Wichita, KS Metropolitan Statistical Area",779,0.1778,Crude Prevalence,48620,448166.002,374237.194,612683.0,73928.808,...,1.060746e+05,64054.803336,56289.731216,62090.819997,48571.431813,7525.617121,96343.974,2628.008888,63178.518688,0.000000
1570,2011,"Wilmington, DE-MD-NJ Metropolitan Division",372,0.1437,Crude Prevalence,37980,4568306.184,3777260.197,5968252.0,791045.987,...,1.120540e+06,735755.109950,652296.663040,684907.946630,475365.055350,63044.792210,369948.521,29998.916678,475925.545926,38421.384639
1584,2011,"Worcester, MA-CT Metropolitan Statistical Area",468,0.1760,Crude Prevalence,49340,614027.564,512761.238,803701.0,101266.326,...,1.418404e+05,93765.116670,78595.528190,93765.116670,47421.573800,6195.108761,154310.592,1657.231462,43584.705230,3492.884546
1597,2011,"Youngstown-Warren-Boardman, OH-PA Metropolitan...",161,0.1765,Crude Prevalence,49660,349496.122,271710.336,446892.0,77785.786,...,9.867386e+04,55817.203340,54801.484000,55116.680000,39091.351400,6790.016698,89991.602,1525.667413,36137.474690,0.000000

In [12]:
t10_merge_df = pd.merge(t10_df, smart_2011, on='cbsacode', suffixes=('', '_smart'), how='left')

t10_merge_df = t10_merge_df.drop(columns=['year_smart'])
t10_merge_df.rename(columns={'year': 'year'}, inplace=True)

In [13]:
t10_merge_df

,cbsacode,depression,user_id,Data_value,v002_rawvalue,v037_rawvalue,v009_rawvalue,v011_rawvalue,v012_rawvalue,v045_rawvalue,...,total_physical_inactivity,total_poor_mental_health_days,total_poor_or_fair_health,total_poor_physical_health_days,total_premature_death,total_primary_care_physicians,total_rural,total_sexually_transmitted_infections,total_uninsured_adults,total_violent_crime
0,10420,8,39,0.205128,87268.059400,58240.750100,173013.555500,195858.809,111324.954700,1957.518676,...,1.367380e+05,8.212452e+04,6.927228e+04,7.465973e+04,49313.040360,8.379800e+03,88225.775,2233.122290,6.288049e+04,0.000000
1,10500,4,15,0.266667,33627.313216,18073.870500,32678.588027,47206.727,17689.738858,1389.102350,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10580,1,24,0.041667,110917.126900,64003.439900,189072.538638,222424.488,158365.739400,2233.395257,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,12060,48,486,0.098765,704567.332121,455224.078200,963351.570397,1392675.744,740003.530616,21640.878648,...,1.781635e+06,1.126446e+06,1.062837e+06,1.133541e+06,767408.891206,1.997964e+05,1691744.892,42173.644426,1.497230e+06,0.000000
4,12100,1,10,0.100000,65413.527600,29781.885300,85816.600800,97169.000,60918.582200,1103.373359,...,7.029138e+04,4.413636e+04,4.964624e+04,4.807949e+04,31185.293866,6.179331e+03,54517.649,1336.769265,4.212724e+04,1784.255373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,46660,4,13,0.307692,26044.599392,14265.858176,34463.764464,41299.180,16477.232106,990.867864,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,46700,2,17,0.117647,59769.542400,28851.411200,66631.052800,103749.344,71963.190400,1908.822592,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,47260,27,170,0.158824,211511.480972,151082.675700,342753.535234,475181.105,265663.166097,9552.280605,...,3.204968e+05,1.742710e+05,1.597110e+05,1.773200e+05,131289.563054,inf,190491.735,12068.462354,1.754131e+05,7383.960488
95,47900,45,401,0.112219,573286.485255,448931.822200,863743.921558,1350874.884,785722.012883,18777.039474,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,49180,3,26,0.115385,108335.578400,60940.302000,157288.753300,172607.848,64041.045400,2812.914974,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
t10_merge_df = t10_merge_df.drop(columns=['Data_value_smart'])

In [15]:
smart_df = pd.concat([smart_df, t10_merge_df], axis=0)

In [16]:
smart_df

,year,Locationdesc,Sample_Size,Data_value,Data_value_type,cbsacode,adult_population,adult_population18_65,population,total_65_and_older,...,v004_rawvalue,v007_rawvalue,v021_rawvalue,v022_rawvalue,v023_rawvalue,v028_rawvalue,v043_rawvalue,v041_rawvalue,v003_rawvalue,CENSUS2010POP
0,2011,"Aberdeen, SD Micropolitan Statistical Area",88.0,0.167500,Crude Prevalence,10100,30312.839,23626.885,39139.0,6685.954000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014,"Aberdeen, SD Micropolitan Statistical Area",105.0,0.193600,Crude Prevalence,10100,31817.000,25031.000,41357.0,6786.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,"Aberdeen, SD Micropolitan Statistical Area",84.0,0.142900,Crude Prevalence,10100,32122.000,25260.000,41948.0,6862.000001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017,"Aberdeen, SD Micropolitan Statistical Area",73.0,0.160500,Crude Prevalence,10100,32650.000,25558.000,42784.0,7092.000002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018,"Aberdeen, SD Micropolitan Statistical Area",89.0,0.207300,Crude Prevalence,10100,32838.000,25643.000,43080.0,7194.999999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,2010,NaN,NaN,0.307692,NaN,46660,NaN,NaN,NaN,NaN,...,0.000868,1.160292e+05,8.374227e+04,2.932177e+04,7558.108,16956.467756,0.000000e+00,1.523716e+05,26638.753,139588.0
93,2010,NaN,NaN,0.117647,NaN,46700,NaN,NaN,NaN,NaN,...,0.003456,2.904568e+05,3.150866e+05,9.219041e+04,28520.736,50745.085186,0.000000e+00,2.530742e+05,64895.008,413344.0
94,2010,"Virginia Beach-Norfolk-Newport News, VA-NC Met...",186.0,0.158824,Crude Prevalence,47260,1285352.401,1089297.754,1695996.0,196054.647000,...,0.015795,1.335754e+06,1.174754e+06,4.488527e+05,72779.011,193701.837471,7.826777e+08,8.597429e+05,230327.504,1693860.0
95,2010,NaN,NaN,0.112219,NaN,47900,NaN,NaN,NaN,NaN,...,0.067928,4.408070e+06,4.500227e+06,2.542420e+06,209600.949,487666.391782,2.569000e+09,6.718948e+06,878906.936,5547495.0
96,2010,NaN,NaN,0.115385,NaN,49180,NaN,NaN,NaN,NaN,...,0.006369,5.375875e+05,4.790592e+05,1.475132e+05,39898.682,62936.938166,0.000000e+00,2.108734e+05,109573.770,640595.0

In [17]:
smart_2019 = smart_df[smart_df['year'] == '2019'].copy()
smart_2019

,year,Locationdesc,Sample_Size,Data_value,Data_value_type,cbsacode,adult_population,adult_population18_65,population,total_65_and_older,...,v004_rawvalue,v007_rawvalue,v021_rawvalue,v022_rawvalue,v023_rawvalue,v028_rawvalue,v043_rawvalue,v041_rawvalue,v003_rawvalue,CENSUS2010POP
5,2019,"Aberdeen, SD Micropolitan Statistical Area",84.0,0.1736,Crude Prevalence,10100,32719.0,2.535700e+04,43097.0,7362.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2019,"Akron, OH Metropolitan Statistical Area",96.0,0.1844,Crude Prevalence,10420,558657.0,4.382940e+05,703505.0,120363.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2019,"Albany-Schenectady-Troy, NY Metropolitan Stati...",136.0,0.1941,Crude Prevalence,10580,711353.0,5.612300e+05,886188.0,150122.999991,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2019,"Albuquerque, NM Metropolitan Statistical Area",254.0,0.1687,Crude Prevalence,10740,706233.0,5.591520e+05,910726.0,147081.000001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,2019,"Anchorage, AK Metropolitan Statistical Area",184.0,0.1721,Crude Prevalence,11260,299926.0,2.572400e+05,400888.0,42686.000010,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548,2019,"Watertown, SD Micropolitan Statistical Area",89.0,0.1583,Crude Prevalence,47980,21291.0,1.650400e+04,28099.0,4787.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1566,2019,"Wichita, KS Metropolitan Statistical Area",415.0,0.2179,Crude Prevalence,48620,473902.0,3.812180e+05,638268.0,92684.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1578,2019,"Wilmington, DE-MD-NJ Metropolitan Division",341.0,0.1890,Crude Prevalence,37980,4766380.0,3.816035e+06,6096120.0,950344.999970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1592,2019,"Worcester, MA-CT Metropolitan Statistical Area",263.0,0.2010,Crude Prevalence,49340,650423.0,5.241940e+05,826116.0,126229.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1601,2019,"Youngstown-Warren-Boardman, OH-PA Metropolitan...",118.0,0.2198,Crude Prevalence,49660,342779.0,2.536080e+05,430176.0,89171.000010,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
t19_df['year'] = '2019'

In [19]:
t19_merge_df = pd.merge(t19_df, smart_2019, on='cbsacode', suffixes=('', '_smart'), how='left')

In [20]:
t19_merge_df = t19_merge_df.drop(columns=['Unnamed: 0'])
t19_merge_df = t19_merge_df.drop(columns=['year_smart'])
t19_merge_df = t19_merge_df.drop(columns=['population_smart'])
t19_merge_df = t19_merge_df.drop(columns=['Data_value_smart'])
t19_merge_df

,cbsacode,population,Data_value,year,Locationdesc,Sample_Size,Data_value_type,adult_population,adult_population18_65,total_65_and_older,...,v004_rawvalue,v007_rawvalue,v021_rawvalue,v022_rawvalue,v023_rawvalue,v028_rawvalue,v043_rawvalue,v041_rawvalue,v003_rawvalue,CENSUS2010POP
0,11460,369208.0,0.233017,2019,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16980,9520784.0,0.178295,2019,"Chicago-Naperville-Elgin, IL-IN-WI Metropolita...",809.0,Crude Prevalence,2.884533e+07,2.354392e+07,5.301412e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17140,2202597.0,0.305031,2019,"Cincinnati, OH-KY-IN Metropolitan Statistical ...",336.0,Crude Prevalence,1.676717e+06,1.351416e+06,3.253010e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,17460,2058549.0,0.284676,2019,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19100,7340943.0,0.247513,2019,"Dallas-Plano-Irving, TX Metropolitan Division",126.0,Crude Prevalence,5.407008e+06,4.602603e+06,8.044050e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,19100,7340943.0,0.247513,2019,"Fort Worth-Arlington, TX Metropolitan Division",115.0,Crude Prevalence,5.407008e+06,4.602603e+06,8.044050e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,19820,4321704.0,0.214972,2019,"Warren-Troy-Farmington Hills, MI Metropolitan ...",472.0,Crude Prevalence,3.352329e+06,2.661840e+06,6.904890e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,23420,986542.0,0.240909,2019,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,25060,412946.0,0.284225,2019,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,26380,209893.0,0.344390,2019,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,26420,6905695.0,0.309480,2019,"Houston-The Woodlands-Sugar Land, TX Metropoli...",484.0,Crude Prevalence,5.070244e+06,4.320558e+06,7.496860e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,28140,2127259.0,0.189866,2019,"Kansas City, MO-KS Metropolitan Statistical Area",851.0,Crude Prevalence,1.609044e+06,1.301575e+06,3.074690e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,29180,490107.0,0.301658,2019,"Lafayette, LA Metropolitan Statistical Area",135.0,Crude Prevalence,3.164480e+05,2.599460e+05,5.650200e+04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,29820,2183310.0,0.180706,2019,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,30820,38837.0,0.320435,2019,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,31080,13298709.0,0.202175,2019,"Los Angeles-Long Beach-Anaheim, CA Metropolita...",467.0,Crude Prevalence,2.084601e+07,1.724563e+07,3.600378e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,31420,229081.0,0.329818,2019,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,33100,6149687.0,0.249395,2019,"Miami-Fort Lauderdale-West Palm Beach, FL Metr...",187.0,Crude Prevalence,1.471862e+07,1.141802e+07,3.300609e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,33460,3577765.0,0.126087,2019,"Minneapolis-St. Paul-Bloomington, MN-WI Metrop...",1681.0,Crude Prevalence,2.733912e+06,2.248279e+06,4.856330e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,35380,1270465.0,0.283349,2019,"New Orleans-Metairie, LA Metropolitan Statisti...",214.0,Crude Prevalence,7.971340e+05,6.448880e+05,1.522460e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,35620,19325698.0,0.190654,2019,"Nassau County-Suffolk County, NY Metropolitan ...",157.0,Crude Prevalence,1.537557e+07,1.238573e+07,2.989838e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,35620,19325698.0,0.190654,2019,"New York-Jersey City-White Plains, NY-NJ Metro...",708.0,Crude Prevalence,1.537557e+07,1.238573e+07,2.989838e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,36660,83447.0,0.306613,2019,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,37980,6078451.0,0.263116,2019,"Montgomery County-Bucks County-Chester County,...",119.0,Crude Prevalence,4.766380e+06,3.816035e+06,9.503450e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,37980,6078451.0,0.263116,2019,"Philadelphia, PA Metropolitan Division",251.0,Crude Prevalence,4.766380e+06,3.816035e+06,9.503450e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,37980,6078451.0,0.263116,2019,"Wilmington, DE-MD-NJ Metropolitan Division",341.0,Crude Prevalence,4.766380e+06,3.816035e+06,9.503450e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,38060,4761694.0,0.208923,2019,"Phoenix-Mesa-Scottsdale, AZ Metropolitan Stati...",524.0,Crude Prevalence,3.593000e+06,2.869322e+06,7.236780e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,38900,2456462.0,0.246445,2019,"Portland-Vancouver-Hillsboro, OR-WA Metropolit...",838.0,Crude Prevalence,1.919542e+06,1.565981e+06,3.535610e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,40060,1269478.0,0.223779,2019,"Richmond, VA Metropolitan Statistical Area",286.0,Crude Prevalence,9.946500e+05,8.024760e+05,1.921740e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,40140,4570427.0,0.209723,2019,"Riverside-San Bernardino-Ontario, CA Metropoli...",245.0,Crude Prevalence,3.392790e+06,2.809170e+06,5.836200e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,41180,2805850.0,0.200000,2019,"St. Louis, MO-IL Metropolitan Statistical Area",449.0,Crude Prevalence,2.181205e+06,1.729538e+06,4.516670e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,41620,1205238.0,0.251232,2019,"Salt Lake City, UT Metropolitan Statistical Area",923.0,Crude Prevalence,8.683840e+05,7.422900e+05,1.260940e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,41740,3325468.0,0.285416,2019,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,41860,4710693.0,0.194789,2019,"Oakland-Hayward-Berkeley, CA Metropolitan Divi...",126.0,Crude Prevalence,3.789090e+06,3.075374e+06,7.137160e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,41940,1993582.0,0.238933,2019,"San Jose-Sunnyvale-Santa Clara, CA Metropolita...",70.0,Crude Prevalence,1.552874e+06,1.290553e+06,2.623210e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,42660,3884469.0,0.250414,2019,"Seattle-Bellevue-Everett, WA Metropolitan Divi...",936.0,Crude Prevalence,3.030528e+06,2.524186e+06,5.063420e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,45940,368602.0,0.259863,2019,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,46140,991610.0,0.312412,2019,"Tulsa, OK Metropolitan Statistical Area",261.0,Crude Prevalence,7.444970e+05,5.954040e+05,1.490930e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,47260,1761305.0,0.249123,2019,"Virginia Beach-Norfolk-Newport News, VA-NC Met...",375.0,Crude Prevalence,1.356833e+06,1.108740e+06,2.480930e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,47580,180019.0,0.310861,2019,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
t19_merge_df['source'] = 'Twitter'
smart_df['source'] = 'Smart'

combined_df = pd.concat([smart_df, t19_merge_df], axis=0)

In [22]:
park_path = '/Users/edison/Desktop/dp/cbsa_park.csv'

In [23]:
park_df = pd.read_csv(park_path)

In [24]:
park_df.rename(columns={'CBSA Code': 'cbsacode'}, inplace=True)

In [25]:
park_df = park_df[['cbsacode', 'Park_Area_Acres', 'Weighted_RESP']].drop_duplicates()

In [26]:
combined_df = pd.merge(combined_df, park_df, on='cbsacode', how='left')

In [27]:
pip install openpyxl

Requirement already satisfied: openpyxl in /Users/edison/anaconda3/envs/mergeagain/lib/python3.8/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/edison/anaconda3/envs/mergeagain/lib/python3.8/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [29]:
file_path = '/Users/edison/Desktop/dp/combined_d3.xlsx'

# Save as Excel file
combined_df.to_excel(file_path, index=False)

print("File saved successfully at:", file_path)

File saved successfully at: /Users/edison/Desktop/dp/combined_d3.xlsx